//Capturar os campos necessários
const tabela = document.querySelector("#tabela-pacientes");
const filtro = document.querySelector("#filtrar‐tabela");
const limparFiltroBtn = document.querySelector("#limpar-filtro");
const botaoAdicionar = document.querySelector("#adicionar-paciente");
const form = document.querySelector("#form-adiciona");
const listaDeErros = document.querySelector("#mensagens-erro");
const pacientes = document.querySelectorAll(".paciente");
const botaoBuscar = document.querySelector("#buscar‐pacientes");
